version: "3.9"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"

  backend:
    build:
      dockerfile: backend.Dockerfile
      args:
        REDIS_HOSTNAME: localhost
        REDIS_PORT: 6379

    depends_on:
      - redis

    ports:
      - 127.0.0.1:3000:80

  web:
    build:
      context: web
      args:
        VITE_API_URL: localhost:3000

    depends_on:
      - backend

    ports:
      - 127.0.0.1:3001:80
