name: backend-ci

on:
  push:
    branches: [main]
    paths:
      - backend/**
      - .github/**
  pull_request:
    paths:
      - backend/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install dependencies
        run: |
          pipenv --version
          python --version
          pipenv install --dev

      - name: Run tests
        run: |
          pipenv run pytest

      - name: Build
        run: |
          pipenv run python -m py_compile main.py

      - name: Check formatting
        run: |
          pipenv run autopep8 --diff --recursive --exit-code .

      - name: Type check
        run: |
          pipenv run mypy main.py --disallow-untyped-defs --ignore-missing-imports
