name: web-ci

on:
  push:
    branches: [main]
    paths:
      - web/**
      - .github/**
  pull_request:
    paths:
      - web/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Install dependencies
        run: |
          npm --version
          node --version
          npm install

      - name: Check lint
        run: |
          npm run lint

      - name: Run tests
        run: |
          npm run test

      - name: Build
        run: |
          npm run build
