name: web-cd

on:
  push:
    branches: [main]
    paths: [web/**]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Build
        env:
          VITE_API_URL: vps.shilangyu.dev
        run: |
          npm install
          npm run build:gh-pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: web/dist
